### ISSUE TITLE
Unused obj parameter in Entity.equals

### ISSUE THREAD

**Issue by arinal** [scalikejdbc/ddd-repository-example#3]
I'm referencing your implementation of Entity for my project and got stuck with code below:
https://github.com/scalikejdbc/ddd-repository-example/blob/master/src/main/scala/j5ik2o/ddd/infrastructure/Entity.scala#L13

```
 override def equals(obj: Any): Boolean = this match {
   case that: Entity[_] => id == that.id
   case _ => false 
}
```

I still couldn't understand why `obj` parameter isn't used, it's as if you're doing equality check between `this.id` and `this.id` which always true.
I'm expecting something like this (from my project):
https://github.com/arinal/dirscan/blob/bdb85e9e45d847af54e560e9a92f066e4b612e80/src/main/scala/commons/Entity.scala

```
override def equals(other: Any): Boolean = other match {
   case that: Entity => id == that.id
   case _ => false
}
```

Btw, I've been doing nice days using ScalikeJDBC, thanks for such a great contribution.

**Comment by xuwei-k** [comment]
Nice catch! thanks
