### ISSUE TITLE
Making the build up-to-date

### ISSUE THREAD

**Issue by seratch** [scalikejdbc/ddd-repository-example#5]
- sbt settings
- versions of dependencies

**Comment by xuwei-k** [comment]
- https://github.com/scalikejdbc/ddd-repository-example/blob/5ef6c15c93519f438f730b20e92fea5c73d36e4f/build.sbt#L2
- https://github.com/skinny-framework/skinny-framework/blob/2.5.2/build.sbt#L10

There is skinny-orm dependency in this example. Skinny-orm 2.5.2 depends on scalikejdbc 3.1.0.
Latest skinny-orm 2.5.2 is compatible with scalikejdbc 3.2.2?

**Comment by seratch** [comment]
No, it isn't. I have a plan to work on skinny 2.6 in a few days. Hopefully, on this weekend.

**Comment by seratch** [comment]
skinny orm 2.6.0 is out.
